[package]
name = "rust-bp-error-handling"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"

[lints.rust]
unsafe_code = "forbid"
# unused = "allow" # for exploratory dev.

[dependencies]
# -- Others
derive_more = {version = "1.0.0-beta", features = ["from"] }
